# Generated by Django 3.0.2 on 2020-01-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200107_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(upload_to='images/emplouees_picture'),
        ),
    ]
