# Generated by Django 3.0.2 on 2020-01-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200107_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the case', max_length=100)),
                ('location', models.CharField(help_text='Enter the location of the case', max_length=100)),
                ('intro', models.TextField(help_text='Enter a brief introduction of this case', max_length=1000)),
            ],
        ),
    ]
