# Generated by Django 3.0.2 on 2020-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200107_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='pictures',
        ),
        migrations.AddField(
            model_name='case',
            name='pictures',
            field=models.ManyToManyField(to='homepage.Image'),
        ),
    ]
